languages: generic

services:
  - dockerfile

before_install:
  - docker build -t timbuckiii/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true timbuckiii/react-test npm test

after_success:
  - docker build -t timbuckiii/multi-client ./client
  - docker build -t timbuckiii/multi-nginx ./nginx
  - docker build -t timbuckiii/multi-server ./server
  - docker build -t timbuckiii/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push timbuckiii/multi-client
  - docker push timbuckiii/multi-nginx
  - docker push timbuckiii/multi-server
  - docker push timbuckiii/multi-worker